USE GD1C2017
GO

PRINT '***************************************'
PRINT '**                                   **'
PRINT '**    script_creacion_inicial.sql    **'
PRINT '**                                   **'
PRINT '**  Gurpo: GESTION_DE_GATOS          **'
PRINT '**  Anio: 2017                       **'
PRINT '**  Integrantes:                     **'
PRINT '**    -Cantero Ezequiel              **'
PRINT '**    -Llopis Ivas Rodrigo           **'
PRINT '**    -Martinez Andres               **'
PRINT '**    -Mico Nicolas                  **'
PRINT '**                                   **'
PRINT '***************************************'

PRINT ''
PRINT ''
PRINT ''
GO

CREATE SCHEMA GESTION_DE_GATOS
GO

PRINT CONCAT(CURRENT_TIMESTAMP, ' - Creando tablas')
PRINT '***************************************************************'
PRINT 'TURNO'
CREATE TABLE GESTION_DE_GATOS.TURNO (
	TURN_ID INT NOT NULL IDENTITY(1,1),
	TURN_INICIO NUMERIC(18,0) NOT NULL,
	TURN_FIN NUMERIC(18,0) NOT NULL,
	TURN_DESCRIPCION VARCHAR(255) NOT NULL,
	TURN_VALOR_KILOMETRO NUMERIC(18,2) NOT NULL,
	TURN_PRECIO_BASE NUMERIC(18,2) NOT NULL,
	TURN_HABILITADO BIT NOT NULL
)

PRINT 'CHOFER'
CREATE TABLE GESTION_DE_GATOS.CHOFER (
	CHOF_ID INT NOT NULL IDENTITY(1,1),
	CHOF_USUARIO INT NOT NULL,
	CHOF_NOMBRE VARCHAR(255) NOT NULL,
	CHOF_APELLIDO VARCHAR(255) NOT NULL,
	CHOF_DNI NUMERIC(18,0) NOT NULL,
	CHOF_DIRECCION VARCHAR(255) NOT NULL,
	CHOF_FECHA_NACIMIENTO DATETIME NOT NULL,
	CHOF_MAIL VARCHAR(50),
	CHOF_TELEFONO NUMERIC(18,0) NOT NULL,
	CHOF_HABILITADO BIT NOT NULL
)

PRINT 'CLIENTE'
CREATE TABLE GESTION_DE_GATOS.CLIENTE (
	CLIE_ID INT NOT NULL IDENTITY(1,1),
	CLIE_USUARIO INT NOT NULL,
	CLIE_NOMBRE VARCHAR(255) NOT NULL,
	CLIE_APELLIDO VARCHAR(255) NOT NULL,
	CLIE_DNI NUMERIC(18,0) NOT NULL,
	CLIE_DIRECCION VARCHAR(255) NOT NULL,
	CLIE_FECHA_NACIMIENTO DATETIME NOT NULL,
	CLIE_MAIL VARCHAR(255),
	CLIE_TELEFONO NUMERIC(18,0) NOT NULL,
	CLIE_HABILITADO BIT NOT NULL
)

PRINT 'USUARIO'
CREATE TABLE GESTION_DE_GATOS.USUARIO (
	USUA_ID INT NOT NULL IDENTITY(1,1),
	USUA_USERNAME CHAR(255) NOT NULL,
	USUA_CONTRASENIA CHAR(255) NOT NULL,
	USUA_HABILITADO BIT NOT NULL
)

PRINT 'ROL'
CREATE TABLE GESTION_DE_GATOS.ROL (
	ROL_ID INT NOT NULL IDENTITY(1,1),
	ROL_DESCRIPCION CHAR(255) NOT NULL,
	ROL_HABILITADO BIT NOT NULL
)

PRINT 'FUNCIONALIDAD'
CREATE TABLE GESTION_DE_GATOS.FUNCIONALIDAD (
	FUNC_ID INT NOT NULL IDENTITY(1,1),
	FUNC_DESCRIPCION CHAR(255) NOT NULL
)

PRINT 'VEHICULO'
CREATE TABLE GESTION_DE_GATOS.VEHICULO (
	VEHI_ID INT NOT NULL IDENTITY(1,1),
	VEHI_MODELO INT NOT NULL,
	VEHI_PATENTE VARCHAR(10) NOT NULL,
	VEHI_LICENCIA VARCHAR(26) NOT NULL,
	VEHI_RODADO VARCHAR(10) NOT NULL,
	VEHI_HABILITADO BIT NOT NULL
)

PRINT 'MODELO'
CREATE TABLE GESTION_DE_GATOS.MODELO (
	MODE_ID INT NOT NULL IDENTITY(1,1),
	MODE_DESCRIPCION VARCHAR(255) NOT NULL,
	MODE_MARCA INT NOT NULL
)

PRINT 'MARCA'
CREATE TABLE GESTION_DE_GATOS.MARCA (
	MARC_ID INT NOT NULL IDENTITY(1,1),
	MARC_DESCRIPCION VARCHAR(255) NOT NULL
)

PRINT 'VIAJE'
CREATE TABLE GESTION_DE_GATOS.VIAJE (
	VIAJ_ID INT NOT NULL IDENTITY(1,1),
	VIAJ_CHOFER INT NOT NULL,
	VIAJ_CLIENTE INT NOT NULL,
	VIAJ_VEHICULO INT NOT NULL,
	VIAJ_TURNO INT NOT NULL,
	VIAJ_DISTANCIA NUMERIC(18,0) NOT NULL,
	VIAJ_FECHA_INICIO DATETIME NOT NULL,
	VIAJ_FECHA_FIN DATETIME NOT NULL
)

PRINT 'FACTURACION'
CREATE TABLE GESTION_DE_GATOS.FACTURACION (
	FACT_ID INT NOT NULL IDENTITY(1,1),
	FACT_FECHA DATETIME NOT NULL,
	FACT_FECHA_INICIO DATETIME NOT NULL,
	FACT_FECHA_FIN DATETIME NOT NULL,
	FACT_IMPROTE FLOAT NOT NULL
)

PRINT 'RENDICION'
CREATE TABLE GESTION_DE_GATOS.RENDICION (
	REND_ID INT NOT NULL IDENTITY(1,1),
	REND_FECHA DATETIME NOT NULL
)

PRINT 'FACTURACION_VIAJE'
CREATE TABLE GESTION_DE_GATOS.FACTURACION_VIAJE (
	FV_FACT_ID INT NOT NULL,
	FV_VIAJ_ID INT NOT NULL,
	FV_IMPORTE FLOAT NOT NULL
)

PRINT 'RENDICION_VIAJE'
CREATE TABLE GESTION_DE_GATOS.RENDICION_VIAJE (
	RV_REND_ID INT NOT NULL,
	RV_VIAJ_ID INT NOT NULL,
	RV_IMPROTE FLOAT NOT NULL
)

PRINT 'ROL_USUARIO'
CREATE TABLE GESTION_DE_GATOS.ROL_USUARIO (
	RU_ROL_ID INT NOT NULL,
	RU_USUA_ID INT NOT NULL
)

PRINT 'FUNCIONALIDAD_ROL'
CREATE TABLE GESTION_DE_GATOS.FUNCIONALIDAD_ROL (
	FR_FUNC_ID INT NOT NULL,
	FR_ROL_ID INT NOT NULL
)

PRINT 'VEHICULO_CHOFER'
CREATE TABLE GESTION_DE_GATOS.VEHICULO_CHOFER (
	VC_VEHI_ID INT NOT NULL,
	VC_CHOF_ID INT NOT NULL,
	VC_TURN_ID INT NOT NULL
)
PRINT '***************************************************************'
PRINT ''

PRINT CONCAT(CURRENT_TIMESTAMP, ' - Creando Restricciones')
PRINT '***************************************************************'
PRINT CONCAT(CURRENT_TIMESTAMP, ' - PKs')
PRINT 'PK_TURN_ID'
ALTER TABLE GESTION_DE_GATOS.TURNO ADD CONSTRAINT PK_TURN_ID PRIMARY KEY (TURN_ID)
PRINT 'PK_CHOF_ID'
ALTER TABLE GESTION_DE_GATOS.CHOFER ADD CONSTRAINT PK_CHOF_ID PRIMARY KEY (CHOF_ID)
PRINT 'PK_CLIE_ID'
ALTER TABLE GESTION_DE_GATOS.CLIENTE ADD CONSTRAINT PK_CLIE_ID PRIMARY KEY (CLIE_ID)
PRINT 'PK_USUA_ID'
ALTER TABLE GESTION_DE_GATOS.USUARIO ADD CONSTRAINT PK_USUA_ID PRIMARY KEY (USUA_ID)
PRINT 'PK_ROL_ID'
ALTER TABLE GESTION_DE_GATOS.ROL ADD CONSTRAINT PK_ROL_ID PRIMARY KEY (ROL_ID)
PRINT 'PK_FUNC_ID'
ALTER TABLE GESTION_DE_GATOS.FUNCIONALIDAD ADD CONSTRAINT PK_FUNC_ID PRIMARY KEY (FUNC_ID)
PRINT 'PK_VEHI_ID'
ALTER TABLE GESTION_DE_GATOS.VEHICULO ADD CONSTRAINT PK_VEHI_ID PRIMARY KEY (VEHI_ID)
PRINT 'PK_MODE_ID'
ALTER TABLE GESTION_DE_GATOS.MODELO ADD CONSTRAINT PK_MODE_ID PRIMARY KEY (MODE_ID)
PRINT 'PK_MARC_ID'
ALTER TABLE GESTION_DE_GATOS.MARCA ADD CONSTRAINT PK_MARC_ID PRIMARY KEY (MARC_ID)
PRINT 'PK_VIAJ_ID'
ALTER TABLE GESTION_DE_GATOS.VIAJE ADD CONSTRAINT PK_VIAJ_ID PRIMARY KEY (VIAJ_ID)
PRINT 'PK_FACT_ID'
ALTER TABLE GESTION_DE_GATOS.FACTURACION ADD CONSTRAINT PK_FACT_ID PRIMARY KEY (FACT_ID)
PRINT 'PK_REND_ID'
ALTER TABLE GESTION_DE_GATOS.RENDICION ADD CONSTRAINT PK_REND_ID PRIMARY KEY (REND_ID)
PRINT 'PK_FV'
ALTER TABLE GESTION_DE_GATOS.FACTURACION_VIAJE ADD CONSTRAINT PK_FV PRIMARY KEY (FV_FACT_ID, FV_VIAJ_ID)
PRINT 'PK_RV'
ALTER TABLE GESTION_DE_GATOS.RENDICION_VIAJE ADD CONSTRAINT PK_RV PRIMARY KEY (RV_REND_ID, RV_VIAJ_ID)
PRINT 'PK_RU'
ALTER TABLE GESTION_DE_GATOS.ROL_USUARIO ADD CONSTRAINT PK_RU PRIMARY KEY (RU_ROL_ID, RU_USUA_ID)
PRINT 'PK_FR'
ALTER TABLE GESTION_DE_GATOS.FUNCIONALIDAD_ROL ADD CONSTRAINT PK_FR PRIMARY KEY (FR_FUNC_ID, FR_ROL_ID)
PRINT 'PK_VC'
ALTER TABLE GESTION_DE_GATOS.VEHICULO_CHOFER ADD CONSTRAINT PK_VC PRIMARY KEY (VC_VEHI_ID, VC_CHOF_ID, VC_TURN_ID)
PRINT ''

PRINT CONCAT(CURRENT_TIMESTAMP, ' - FKs')
PRINT 'FK_CHOF_USUA'
ALTER TABLE GESTION_DE_GATOS.CHOFER ADD CONSTRAINT FK_CHOF_USUA FOREIGN KEY (CHOF_USUARIO) REFERENCES GESTION_DE_GATOS.USUARIO(USUA_ID)
PRINT 'FK_CLIE_USUA'
ALTER TABLE GESTION_DE_GATOS.CLIENTE ADD CONSTRAINT FK_CLIE_USUA FOREIGN KEY (CLIE_USUARIO) REFERENCES GESTION_DE_GATOS.USUARIO(USUA_ID)
PRINT 'FK_VEHI_MODE'
ALTER TABLE GESTION_DE_GATOS.VEHICULO ADD CONSTRAINT FK_VEHI_MODE FOREIGN KEY (VEHI_MODELO) REFERENCES GESTION_DE_GATOS.MODELO(MODE_ID)
PRINT 'FK_MODE_MARC'
ALTER TABLE GESTION_DE_GATOS.MODELO ADD CONSTRAINT FK_MODE_MARC FOREIGN KEY (MODE_MARCA) REFERENCES GESTION_DE_GATOS.MARCA(MARC_ID)
PRINT 'FK_VIAJ_CHOF'
ALTER TABLE GESTION_DE_GATOS.VIAJE ADD CONSTRAINT FK_VIAJ_CHOF FOREIGN KEY (VIAJ_CHOFER) REFERENCES GESTION_DE_GATOS.CHOFER(CHOF_ID)
PRINT 'FK_VIAJ_CLIE'
ALTER TABLE GESTION_DE_GATOS.VIAJE ADD CONSTRAINT FK_VIAJ_CLIE FOREIGN KEY (VIAJ_CLIENTE) REFERENCES GESTION_DE_GATOS.CLIENTE(CLIE_ID)
PRINT 'FK_VIAJ_VEHI'
ALTER TABLE GESTION_DE_GATOS.VIAJE ADD CONSTRAINT FK_VIAJ_VEHI FOREIGN KEY (VIAJ_VEHICULO) REFERENCES GESTION_DE_GATOS.VEHICULO(VEHI_ID)
PRINT 'FK_VIAJ_TURN'
ALTER TABLE GESTION_DE_GATOS.VIAJE ADD CONSTRAINT FK_VIAJ_TURN FOREIGN KEY (VIAJ_TURNO) REFERENCES GESTION_DE_GATOS.TURNO(TURN_ID)
PRINT 'FK_FV_VEHI'
ALTER TABLE GESTION_DE_GATOS.FACTURACION_VIAJE ADD CONSTRAINT FK_FV_VEHI FOREIGN KEY (FV_FACT_ID) REFERENCES GESTION_DE_GATOS.FACTURACION(FACT_ID)
PRINT 'FK_FV_VIAJ'
ALTER TABLE GESTION_DE_GATOS.FACTURACION_VIAJE ADD CONSTRAINT FK_FV_VIAJ FOREIGN KEY (FV_VIAJ_ID) REFERENCES GESTION_DE_GATOS.VIAJE(VIAJ_ID)
PRINT 'FK_RV_REND'
ALTER TABLE GESTION_DE_GATOS.RENDICION_VIAJE ADD CONSTRAINT FK_RV_REND FOREIGN KEY (RV_REND_ID) REFERENCES GESTION_DE_GATOS.RENDICION(REND_ID)
PRINT 'FK_RV_VIAJ'
ALTER TABLE GESTION_DE_GATOS.RENDICION_VIAJE ADD CONSTRAINT FK_RV_VIAJ FOREIGN KEY (RV_VIAJ_ID) REFERENCES GESTION_DE_GATOS.VIAJE(VIAJ_ID)
PRINT 'FK_RU_ROL'
ALTER TABLE GESTION_DE_GATOS.ROL_USUARIO ADD CONSTRAINT FK_RU_ROL FOREIGN KEY (RU_ROL_ID) REFERENCES GESTION_DE_GATOS.ROL(ROL_ID)
PRINT 'FK_RU_USUA'
ALTER TABLE GESTION_DE_GATOS.ROL_USUARIO ADD CONSTRAINT FK_RU_USUA FOREIGN KEY (RU_USUA_ID) REFERENCES GESTION_DE_GATOS.USUARIO(USUA_ID)
PRINT 'FK_FR_FUNC'
ALTER TABLE GESTION_DE_GATOS.FUNCIONALIDAD_ROL ADD CONSTRAINT FK_FR_FUNC FOREIGN KEY (FR_FUNC_ID) REFERENCES GESTION_DE_GATOS.FUNCIONALIDAD(FUNC_ID)
PRINT 'FK_FR_ROL'
ALTER TABLE GESTION_DE_GATOS.FUNCIONALIDAD_ROL ADD CONSTRAINT FK_FR_ROL FOREIGN KEY (FR_ROL_ID) REFERENCES GESTION_DE_GATOS.ROL(ROL_ID)
PRINT 'FK_VC_VEHI'
ALTER TABLE GESTION_DE_GATOS.VEHICULO_CHOFER ADD CONSTRAINT FK_VC_VEHI FOREIGN KEY (VC_VEHI_ID) REFERENCES GESTION_DE_GATOS.VEHICULO(VEHI_ID)
PRINT 'FK_VC_CHOF'
ALTER TABLE GESTION_DE_GATOS.VEHICULO_CHOFER ADD CONSTRAINT FK_VC_CHOF FOREIGN KEY (VC_CHOF_ID) REFERENCES GESTION_DE_GATOS.CHOFER(CHOF_ID)
PRINT 'FK_VC_TURN'
ALTER TABLE GESTION_DE_GATOS.VEHICULO_CHOFER ADD CONSTRAINT FK_VC_TURN FOREIGN KEY (VC_TURN_ID) REFERENCES GESTION_DE_GATOS.TURNO(TURN_ID)
PRINT '***************************************************************'
PRINT ''

PRINT CONCAT(CURRENT_TIMESTAMP, ' - Creando objetos necesarios pre migracion')
PRINT '***************************************************************'
PRINT 'Funcion encriptar_contrasenia'
GO

CREATE FUNCTION GESTION_DE_GATOS.encriptar_contrasenia(@contrasenia CHAR(255))
RETURNS CHAR(255)
AS
BEGIN
	RETURN HASHBYTES('SHA2_256', @contrasenia)
END
GO

PRINT 'Stored Procedure ejecutar_migracion'
GO

CREATE PROCEDURE GESTION_DE_GATOS.ejecutar_migracion
AS
	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Comenzando migracion...')

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando tablas maestras')
	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando TURNO')
	INSERT GESTION_DE_GATOS.TURNO (TURN_INICIO, TURN_FIN, TURN_DESCRIPCION, TURN_VALOR_KILOMETRO, TURN_PRECIO_BASE, TURN_HABILITADO)
	(
		SELECT Turno_Hora_Inicio, Turno_Hora_Fin, Turno_Descripcion, Turno_Valor_Kilometro, Turno_Precio_Base, CAST(1 AS BIT)
		FROM gd_esquema.Maestra
		GROUP BY Turno_Hora_Inicio, Turno_Hora_Fin, Turno_Descripcion, Turno_Valor_Kilometro, Turno_Precio_Base
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando MARCA')
	INSERT GESTION_DE_GATOS.MARCA (MARC_DESCRIPCION)
	(
		SELECT Auto_Marca
		FROM gd_esquema.Maestra
		GROUP BY Auto_Marca
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando MODELO')
	INSERT GESTION_DE_GATOS.MODELO (MODE_DESCRIPCION, MODE_MARCA)
	(
		SELECT Auto_Modelo, MARC_ID
		FROM gd_esquema.Maestra JOIN MARCA ON Auto_Marca = MARC_DESCRIPCION
		GROUP BY Auto_Modelo, MARC_ID
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando VEHICULO')
	INSERT GESTION_DE_GATOS.VEHICULO (VEHI_MODELO, VEHI_PATENTE, VEHI_LICENCIA, VEHI_RODADO, VEHI_HABILITADO)
	(
		SELECT MODE_ID, Auto_Patente, Auto_Licencia, Auto_Rodado, CAST(1 AS BIT)
		FROM gd_esquema.Maestra JOIN GESTION_DE_GATOS.MODELO ON Auto_Modelo = MODE_DESCRIPCION
		GROUP BY MODE_ID, Auto_Patente, Auto_Licencia, Auto_Rodado
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando ROL')
	INSERT GESTION_DE_GATOS.ROL (ROL_DESCRIPCION, ROL_HABILITADO) VALUES ('Administrador', CAST(1 AS BIT))
	INSERT GESTION_DE_GATOS.ROL (ROL_DESCRIPCION, ROL_HABILITADO) VALUES ('Cliente', CAST(1 AS BIT))
	INSERT GESTION_DE_GATOS.ROL (ROL_DESCRIPCION, ROL_HABILITADO) VALUES ('Chofer', CAST(1 AS BIT))


	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando USUARIO')
	--Creo usuario administrador
	INSERT GESTION_DE_GATOS.USUARIO (USUA_USERNAME, USUA_CONTRASENIA, USUA_HABILITADO) VALUES ('admin', (SELECT GESTION_DE_GATOS.encriptar_contrasenia('w23e')), CAST(1 AS BIT))

	--Creo usuarios en base a choferes
	INSERT GESTION_DE_GATOS.USUARIO (USUA_USERNAME, USUA_CONTRASENIA, USUA_HABILITADO)
	(
		SELECT CONVERT(CHAR(255), Chofer_Dni), (SELECT GESTION_DE_GATOS.encriptar_contrasenia(CONVERT(CHAR(255), Chofer_Dni))), CAST(1 AS BIT)
		FROM gd_esquema.Maestra
		GROUP BY Chofer_Dni
	)

	--Creo usuarios en base a clientes
	INSERT GESTION_DE_GATOS.USUARIO (USUA_USERNAME, USUA_CONTRASENIA, USUA_HABILITADO)
	(
		SELECT CONVERT(CHAR(255), Cliente_Dni), (SELECT GESTION_DE_GATOS.encriptar_contrasenia(CONVERT(CHAR(255), Cliente_Dni))), CAST(1 AS BIT)
		FROM gd_esquema.Maestra
		WHERE CONVERT(CHAR(255), Cliente_Dni) not in (
			SELECT USUA_USERNAME
			FROM GESTION_DE_GATOS.USUARIO	
		)
		GROUP BY Cliente_Dni
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando CHOFER')
	INSERT GESTION_DE_GATOS.CHOFER (CHOF_USUARIO, CHOF_NOMBRE, CHOF_APELLIDO, CHOF_DNI, CHOF_DIRECCION, CHOF_FECHA_NACIMIENTO, CHOF_MAIL, CHOF_TELEFONO, CHOF_HABILITADO)
	(
		SELECT (SELECT USUA_ID FROM GESTION_DE_GATOS.USUARIO WHERE USUA_USERNAME = CONVERT(CHAR(255), Chofer_Dni)), Chofer_Nombre, Chofer_Apellido, Chofer_Dni, Chofer_Direccion, Chofer_Fecha_Nac, Chofer_Mail, Chofer_Telefono, CAST(1 AS BIT)
		FROM gd_esquema.Maestra
		GROUP BY Chofer_Nombre, Chofer_Apellido, Chofer_Dni, Chofer_Direccion, Chofer_Fecha_Nac, Chofer_Mail, Chofer_Telefono
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando CLIENTE')
	INSERT GESTION_DE_GATOS.CLIENTE (CLIE_USUARIO, CLIE_NOMBRE, CLIE_APELLIDO, CLIE_DNI, CLIE_DIRECCION, CLIE_FECHA_NACIMIENTO, CLIE_MAIL, CLIE_TELEFONO, CLIE_HABILITADO)
	(
		SELECT (SELECT USUA_ID FROM GESTION_DE_GATOS.USUARIO WHERE USUA_USERNAME = CONVERT(CHAR(255), Cliente_Dni)), Cliente_Nombre, Cliente_Apellido, Cliente_Dni, Cliente_Direccion, Cliente_Fecha_Nac, Cliente_Mail, Cliente_Telefono, CAST(1 AS BIT)
		FROM gd_esquema.Maestra
		GROUP BY Cliente_Nombre, Cliente_Apellido, Cliente_Dni, Cliente_Direccion, Cliente_Fecha_Nac, Cliente_Mail, Cliente_Telefono
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando ROL_USUARIO')
	--Migro usuarios de Choferes
	INSERT GESTION_DE_GATOS.ROL_USUARIO (RU_ROL_ID, RU_USUA_ID)
	(
		SELECT (SELECT ROL_ID FROM GESTION_DE_GATOS.ROL WHERE ROL_DESCRIPCION = 'Chofer'), USUA_ID
		FROM gd_esquema.Maestra
			JOIN GESTION_DE_GATOS.USUARIO ON CONVERT(CHAR(255), Chofer_Dni) = USUA_USERNAME
		GROUP BY USUA_ID
	)

	--Migro usuarios por Clientes
	INSERT GESTION_DE_GATOS.ROL_USUARIO (RU_ROL_ID, RU_USUA_ID)
	(
		SELECT (SELECT ROL_ID FROM GESTION_DE_GATOS.ROL WHERE ROL_DESCRIPCION = 'Cliente'), USUA_ID
		FROM gd_esquema.Maestra
			JOIN GESTION_DE_GATOS.USUARIO ON CONVERT(CHAR(255), Cliente_Dni) = USUA_USERNAME
		GROUP BY USUA_ID
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando VEHICULO_CHOFER')
	INSERT GESTION_DE_GATOS.VEHICULO_CHOFER (VC_VEHI_ID, VC_CHOF_ID, VC_TURN_ID)
	(
		SELECT VEHI_ID, CHOF_ID, (SELECT TURN_ID FROM GESTION_DE_GATOS.TURNO WHERE TURN_DESCRIPCION = Turno_Descripcion)
		FROM gd_esquema.Maestra
			JOIN GESTION_DE_GATOS.VEHICULO ON Auto_Patente = VEHI_PATENTE
			JOIN GESTION_DE_GATOS.CHOFER ON Chofer_Dni = CHOF_DNI
		GROUP BY VEHI_ID, CHOF_ID, Turno_Descripcion
	)

	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Migrando tablas transaccionales')



	PRINT CONCAT(CURRENT_TIMESTAMP, ' - Fin migracion...')
GO
PRINT '***************************************************************'
PRINT ''

PRINT 'Ejecutando migracion'
PRINT '***************************************************************'
EXEC GESTION_DE_GATOS.ejecutar_migracion
PRINT '***************************************************************'
GO